server:
  port: 12000
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/xiamo1024/t-config.git
  rabbitmq:
    host: www.qikecloud.com
    username: buke
    password: buke~123
management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh