server:
  port: 9006
spring:
  application:
    name: tensquare-spit
  data:
    mongodb:
      host: www.qikeCloud.com
      username: root
      password: buke~123
      database: spitdb
  redis:
    host: www.qikeCloud.com
    port: 6399
    password: buke~123456
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
